name: "Performing the base validation"
description: "Performing the base validation check against the onboarding.yml"

runs:
  using: composite

  steps:
    - name: checkout schema
      uses: actions/checkout@v7
      with:
        repository: ${{ github.repository_owner }}/tets-repo
        path: IPU-v2/schema
        ref: main

    - name: validating the Configuration
      shell: bash
      run: |
        pip install check-jsonschema
        check-jsonschema --schemafile IPU-v2/schema/in-place-upgrade-schema.json in-place-upgrade-onboarding.yml
