name: "Performing the base validation"
description: "Performing the base validation check against the onboarding.yml"

runs:
  using: composite

  steps:
    - name: checkout schema
      uses: actions/checkout@v7
      with:
        repository: ${{ github.repository_owner }}/tets-repo
        path: central-schema
        ref: main
        sparse-checkout: IPU-v2/schema/in-place-upgrade-schema.json

    - name: validating the Configuration
      shell: bash
      run: |
        ls -lrta
        find . -name in-place-upgrade-schema.json
        cat $(find . -name in-place-upgrade-schema.json) | grep maxL | grep minL
        pip install check-jsonschema
        check-jsonschema --schemafile central-schema/IPU-v2/schema/in-place-upgrade-schema.json in-place-upgrade-onboarding.yml
